In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('petrol.csv')

In [3]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df = df[(df > (Q1 - 1.5 * IQR)) & (df < (Q3 + 1.5 * IQR))]
df.dropna(axis=0,inplace=True)

In [4]:
def SingleDLinearRegression(x,y):
    p1 = x.dot(x)
    p2 = x.sum()
    p3 = x.sum()
    p4 = x.shape[0]
    p5 = x.dot(y)
    p6 = y.sum()
    mat1 = [[p1,p2],[p3,p4]]
    mat2 = [[p5],[p6]]
    inv_mat1 = np.linalg.inv(mat1)
    coffmat = inv_mat1.dot(mat2)
    a= coffmat[0,0]
    b = coffmat[1,0]
    ymean = y - y.mean()
    yhat = a*x+b
    y_1 = y - yhat
    r2 = 1 - ((y_1.dot(y_1))/(ymean.dot(ymean)))
    return coffmat,r2
    

In [5]:
def MultiDLinearRegression(x,y):
    x_x = x.T.dot(x)
    x_y = x.T.dot(y)
    invx_x = np.linalg.inv(x_x)
    coffmat = invx_x.dot(x_y)
    yhat = x.dot(coffmat)
    ymean = y - y.mean()
    y_1 = y - yhat
    r2 = 1 - ((y_1.dot(y_1))/(ymean.dot(ymean)))
    return coffmat,r2

In [6]:
X = df[["tax"," income"," highway"," dl"]]
Y = df[[" consumption"]]
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, 
                                                    random_state=1)

In [7]:
x_tax = x_train[["tax"]]
x_income = x_train[[" income"]]
x_highway = x_train[[" highway"]]
x_dl = x_train[[" dl"]]
y_trainflat = y_train.values.flatten()
x_tax = x_tax.values.T
x_taxflat = x_tax.flatten()
x_income = x_income.values.T
x_incomeflat = x_income.flatten()
x_highway = x_highway.values.T
x_highwayflat = x_highway.flatten()
x_dl = x_dl.values.T
x_dlflat = x_dl.flatten()

In [8]:
taxd,taxr2 = SingleDLinearRegression(x_taxflat,y_trainflat)

In [9]:
print(taxd)
print(taxr2)

[[-48.35145299]
 [930.17367521]]
0.2015013363098892


In [10]:
incomed,incomer2 = SingleDLinearRegression(x_incomeflat,y_trainflat)

In [11]:
print(incomed)
print(incomer2)

[[-4.06155080e-02]
 [ 7.30131164e+02]]
0.07094959259830802


In [12]:
highwayd,highwayr2 = SingleDLinearRegression(x_highwayflat,y_trainflat)

In [13]:
print(highwayd)
print(highwayr2)

[[-2.26324371e-03]
 [ 5.70180075e+02]]
0.005515527542538923


In [14]:
dld,dlr2 = SingleDLinearRegression(x_dlflat,y_trainflat)

In [15]:
print(dld)
print(dlr2)

[[1036.11061885]
 [ -24.15241936]]
0.39199458409851096


In [52]:
x_t =  x_train[["tax"," income"," highway"," dl"]]

In [53]:
x_tv = x_t.values
x_tv.shape[0]
ons = np.ones((x_tv.shape[0],1))
x_tv = np.hstack((ons,x_tv))
x_tv

array([[1.0000e+00, 9.0000e+00, 4.8970e+03, 2.4490e+03, 5.1100e-01],
       [1.0000e+00, 8.5000e+00, 4.5740e+03, 2.6190e+03, 5.5100e-01],
       [1.0000e+00, 8.5000e+00, 3.6350e+03, 3.2740e+03, 6.6300e-01],
       [1.0000e+00, 8.0000e+00, 3.0630e+03, 6.5240e+03, 5.7800e-01],
       [1.0000e+00, 7.0000e+00, 4.4490e+03, 4.6390e+03, 6.2600e-01],
       [1.0000e+00, 8.0000e+00, 3.5280e+03, 3.4950e+03, 4.8700e-01],
       [1.0000e+00, 7.0000e+00, 3.8970e+03, 6.3850e+03, 5.8600e-01],
       [1.0000e+00, 6.0000e+00, 5.2150e+03, 2.3020e+03, 6.7200e-01],
       [1.0000e+00, 8.0000e+00, 4.3990e+03, 4.3100e+02, 5.4400e-01],
       [1.0000e+00, 8.0000e+00, 3.4480e+03, 5.3990e+03, 5.4800e-01],
       [1.0000e+00, 7.0000e+00, 4.2060e+03, 8.5080e+03, 5.7200e-01],
       [1.0000e+00, 7.0000e+00, 4.8170e+03, 6.9300e+03, 5.7400e-01],
       [1.0000e+00, 7.0000e+00, 3.7450e+03, 2.6110e+03, 5.0800e-01],
       [1.0000e+00, 7.0000e+00, 3.6400e+03, 6.9050e+03, 5.1800e-01],
       [1.0000e+00, 9.0000e+00, 3.

In [54]:
d,r2 = MultiDLinearRegression(x_tv,y_trainflat)

In [55]:
print(d)
print(r2)

[ 6.07718909e+02 -3.94115836e+01 -6.26281401e-02 -3.02198704e-03
  9.50882744e+02]
0.6407622941321006


In [23]:
X1=[]
Y1=[]
for r in open('data_2d.csv'):
    x1,x2,y = r.split(',')
    X1.append([1,float(x1),float(x2)])
    Y1.append(float(y))

X1 = np.array(X1)
Y1 = np.array(Y1)

In [24]:
d2,r22 = MultiDLinearRegression(X1,Y1)

In [25]:
print(d2)
print(r22)

[1.46191241 2.01666793 2.96985048]
0.9980040612475777
